server:
  port: 8083
spring:
  application:
    name: simpleCustomerUser
eureka:
  client:
    serviceUrl:
      defaultZone: http://user:123123@localhost:8571/simpleDiscoveryEureka/eureka/      # 与Eureka Server 交互的地址
    instance:
      prefer-ip-address: true